#!/usr/bin/env bash
# Copies ABIs from contracts/out into packages/abi (I-0.5, I-1.7). Run from anywhere.
#   packages/abi/<Name>.json  plain ABI JSON (Envio's contract import reads these)
#   packages/abi/abis.ts      the same ABIs `as const`, so viem types every call
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
dest="$here/../packages/abi"
cd "$here" && forge build --silent

ts="$dest/abis.ts"
echo "// Generated by contracts/scripts/export-abi.sh. Do not edit by hand." > "$ts"
# contract name → exported TS name (must match packages/abi/index.ts)
for pair in CampaignVault:campaignVaultAbi CampaignVaultLens:campaignVaultLensAbi CreatorReputation:creatorReputationAbi MockUSDC:mockUsdcAbi; do
  name="${pair%%:*}" var="${pair##*:}"
  jq '.abi' "out/$name.sol/$name.json" > "$dest/$name.json"
  { echo; echo "export const $var = $(jq '.abi' "out/$name.sol/$name.json") as const;"; } >> "$ts"
  echo "wrote packages/abi/$name.json"
done
echo "wrote packages/abi/abis.ts"
